### ISSUE TITLE
Recieving a PM from someone you haven't PM'd is broken

### ISSUE THREAD

**Issue by LolcatsV2** [suchipi/nutti-issues#15]
Wouldn't get notifications in any tab open until I opened a PM with them, and even then i got the notification in their room only (both sound and the red counter next to their name).

**Comment by suchipi** [comment]
Darn, I thought I got that working. Ok, thanks

**Comment by suchipi** [comment]
Note to self: investigate using https://github.com/peerlibrary/meteor-reactive-publish to resolve this

**Comment by suchipi** [comment]
Project not maintained; closing
